### ISSUE TITLE
Restarting 0.19.3 operator causes restarts on ClickHouse cluster

### ISSUE THREAD

**Issue by cw9** [Altinity/clickhouse-operator#1032] opened 2022-10-21 03:53 UTC
Hi, I recently upgraded my operator to 0.19.3 trying to fix the issue that sometimes restarting the 0.18.4 operator would cause restart in the CH cluster and break remote-servers.xml, but I'm continuing to see the same behavior with 0.19.3, even more consistently than before, the CH cluster is being restarted every time the operator is restarted. I tried re-deploy the ClickHouse crd but still no help.

Some error messages that seems interesting are:
```
E1021 03:44:35.463687       1 controller.go:797] doUpdateCHIObjectStatus():foo/bar/92a639a9-c200-4e21-9f33-33337df297ae:"Operation cannot be fulfilled on clickhouseinstallations.clickhouse.altinity.com \"bar\": the object has been modified; please apply your changes to the latest version and try again"

E1021 03:45:06.084753       1 creator.go:76] updateStatefulSet():StatefulSet.apps "chi-bar-baz-0-1" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
I1021 03:45:06.084792       1 worker.go:2149] updateStatefulSet():Update StatefulSet(foo/chi-bar-baz-0-1) switch from Update to Recreate
E1021 03:45:06.154667       1 worker.go:2153] updateStatefulSet():Update StatefulSet(foo/chi-bar-baz-0-1) - failed with error
---
StatefulSet.apps "chi-bar-baz-0-1" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
--
```

Did I miss anything in the upgrade?

**Comment by alex-zaitsev** [comment] 2022-10-23 09:20
Hi @cw9 , we are struggling to fix this issue now, you can see that releases 0.19.2 and 0.19.3 addressed it at some extent but the rebuild of remote_servers.xml is still happening sometimes for us as well.

Expect a fix later this week, it could be 0.19.4 or 0.20.0 release (0.20.0 has some really good features coming).

**Comment by alex-zaitsev** [comment] 2022-10-23 09:21
However, looking into your log example --  it does not seem to be caused by an operator restart but a change in CHI.

**Comment by alex-zaitsev** [comment] 2022-11-01 14:55
Hi @cw9 , please try 0.20.0 version. The problem should be fixed

**Comment by alex-zaitsev** [comment] 2022-11-04 20:19
Hi @cw9 , under what conditions do you see restart of CH cluster? We can not reproduce it. We test restart of an operator as a part of our release process, and it does not restart CH clusters.

**Comment by cw9** [comment] 2022-11-07 18:48
I was testing through killing the operator pod, then the operator will be restarted by k8s and start restarting the CH clusters

**Comment by alex-zaitsev** [comment] 2022-11-08 02:52
Hi @cw9 , could you post the log from operator pod after a restart, please? Operator should do a re-conciliation, since the operator pod IP changes during the restart, but it does not require restart of the ClickHouse cluster.

**Closed** 2023-01-20 15:36 UTC
