### ISSUE TITLE
wrong users generation causing clickhouse crash 

### ISSUE THREAD

**Issue by salimidruide** [Altinity/clickhouse-operator#1332] opened 2024-02-05 11:31 UTC
Hello there,

After the upgrade to clickhouse-operator 0.23.0 , we noticed that the ClickHouseInstallation object has some erroneous injected users configuration:
`        users:
          /networks/ip:
            - 10.2.2.100
          /profile: clickhouse_operator
          default/networks/host_regexp: >-
            (chi-clickhouse-[^.]+\d+-\d+|clickhouse\-clickhouse)\.analytics\.svc\.cluster\.local$
          default/networks/ip:
            - '::1'
            - 127.0.0.1
            - 10.2.14.136
          default/profile: default`
          
  It seems that the operator is injecting "empty"/networks.. "empty"/profile.
  Clickhouse-server is trying then to parse the generated configuration and crashing with the error: 
  
` <Error> Application: Code: 36. DB::Exception: Either 'password' or 'password_sha256_hex' or 'password_double_sha1_hex' or 'no_password' or 'ldap' or 'kerberos or 'ssl_certificates' or 'ssh_keys' or 'http_authentication' must be specified for user networks.: while parsing user 'networks' in users configuration file: while loading configuration file '/etc/clickhouse-server/users.xml'. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):`

I am using the lasted clickhouse-server version: clickhouse/clickhouse-server:23.11.5-alpine (self-hosted on Kubernetes).

is there a way to fix it? a turn around ? 
Thank you in advance

**Comment by sunsingerus** [comment] 2024-02-07 14:09
Found the reason, work in progress. Please, keep an eye on operatorhub releases, will publish 0.23.1 soon

**Comment by sunsingerus** [comment] 2024-02-07 14:16
@salimidruide thanks for detailed description of the case, this really helped to reproduce and to catch the issue

**Comment by alex-zaitsev** [comment] 2024-02-12 15:49
Fixed in https://github.com/Altinity/clickhouse-operator/releases/tag/release-0.23.1

**Closed by alex-zaitsev** 2024-02-12 15:49 UTC
