### ISSUE TITLE
Error during downgrading Clickhouse version - forbidden 

### ISSUE THREAD

**Issue by wiktor2200** [Altinity/clickhouse-operator#453] opened 2020-07-06 15:03 UTC
I've updated (downgrade) Clickhouse from 20.4 version to Altinity stable version 20.3.12 and I've removed configuration of external load balancer (commented out in code):
```
  templates:
    serviceTemplates:
      # - name: clickhouse-service-with-external-lb-template
      #   generateName: "clickhouse-service-external-{chi}"
      #   spec:
      #     ports:
      #       - name: http
      #         port: 8123
      #     type: LoadBalancer
```
And downgrade section:
```
podTemplates:
    spec:
      containers:
        - name: clickhouse-pod
          image: yandex/clickhouse-server:20.3.12.112
```
And then I run `kubectl apply` for this yaml file. It seems to be OK, I've got status: `configured` and pods have reloaded.
But after some hours I've noticed that one of pods is missing table config. Running `CREATE TABLE ON CLUSTER` has helped, but I was looking for the reason of such problem.
Problem encountered only on one pod, rest of them updated smoothly.

I've found some logs relating to this case:
```
Update ConfigMap live-clickhouse-operator/chi-analytics-2-deploy-confd-ch-cluster-0-0
--
getPodTemplate() statefulSet chi-analytics-2-ch-cluster-0-0 use custom template clickhouse-with-volumes-template
Update StatefulSet live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0 - started
Update StatefulSet live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0 - failed with error StatefulSet.apps "chi-analytics-2-ch-cluster-0-0" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Reconcile Host 0-0 failed to reconcile StatefulSet chi-analytics-2-ch-cluster-0-0
FAILED update: StatefulSet.apps "chi-analytics-2-ch-cluster-0-0" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: watch of *v1.ClickHouseInstallation ended with: too old resource version: 14055644 (14056680)
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: watch of *v1.ClickHouseInstallationTemplate ended with: too old resource version: 33459 (14056683)
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseOperatorConfiguration: unknown (get clickhouseoperatorconfigurations.clickhouse.altinity.com)
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseOperatorConfiguration: clickhouseoperatorconfigurations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseoperatorconfigurations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallation: clickhouseinstallations.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallations" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
github.com/altinity/clickhouse-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1.ClickHouseInstallationTemplate: clickhouseinstallationtemplates.clickhouse.altinity.com is forbidden: User "system:serviceaccount:live-clickhouse-operator:clickhouse-operator" cannot list resource "clickhouseinstallationtemplates" in API group "clickhouse.altinity.com" in the namespace "live-clickhouse-operator"
FAILED Query(http://***:***@chi-analytics-2-ch-cluster-0-0.live-clickhouse-operator.svc.cluster.local:8123/) read tcp 10.5.x.x:58448->10.x.x.x:8123: read: connection reset by peer for SQL:   	SELECT
```

```
CreateServiceShard(live-clickhouse-operator/shard-analytics-2-ch-cluster-1) 
Reconcile Host 0-0 started 
Update ConfigMap live-clickhouse-operator/chi-analytics-2-deploy-confd-ch-cluster-0-0 
getPodTemplate() statefulSet chi-analytics-2-ch-cluster-0-0 use custom template clickhouse-with-volumes-template 
Update StatefulSet(live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0) - started 
Update StatefulSet(live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0) - failed with error 
---
StatefulSet.apps "chi-analytics-2-ch-cluster-0-0" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
--
Continue with recreate
StatefulSet.Spec diff: 
added items: 1 
ap item path:.Selector.MatchLabels["clickhouse.altinity.com/namespace"]
ap item value:live-clickhouse-operator
-------------------------
modified spec items: 26
ap item path:.UpdateStrategy.RollingUpdate
ap item value:nil
ap item path:.Template.ObjectMeta.Labels["clickhouse.altinity.com/chop"]
ap item value:0.10.0
ap item path:.Template.ObjectMeta.Annotations
ap item value:map[]
ap item path:.Template.Spec.Containers[0].Image
ap item value:yandex/clickhouse-server:20.3.12.112
ap item path:.Template.Spec.Containers[0].TerminationMessagePath
ap item value:
ap item path:.Template.Spec.Containers[0].TerminationMessagePolicy
ap item value:
ap item path:.Template.Spec.Affinity.PodAntiAffinity.PreferredDuringSchedulingIgnoredDuringExecution
ap item value:[]
ap item path:.VolumeClaimTemplates[0].TypeMeta.APIVersion
ap item value:v1
ap item path:.Template.Spec.InitContainers[0].TerminationMessagePath
ap item value:
ap item path:.Template.Spec.RestartPolicy
ap item value:
ap item path:.Template.Spec.Affinity.NodeAffinity.PreferredDuringSchedulingIgnoredDuringExecution
ap item value:[]
ap item path:.VolumeClaimTemplates[0].TypeMeta.Kind
ap item value:PersistentVolumeClaim
ap item path:.VolumeClaimTemplates[0].ObjectMeta.Labels
ap item value:map[clickhouse.altinity.com/app:chop clickhouse.altinity.com/chi:analytics-2 clickhouse.altinity.com/chiScopeCycleIndex:0 clickhouse.altinity.com/chiScopeCycleOffset:2 clickhouse.altinity.com/chiScopeCycleSize:0 clickhouse.altinity.com/chiScopeIndex:2 clickhouse.altinity.com/chop:0.10.0 clickhouse.altinity.com/cluster:ch-cluster clickhouse.altinity.com/clusterScopeCycleIndex:0 clickhouse.altinity.com/clusterScopeCycleOffset:2 clickhouse.altinity.com/clusterScopeCycleSize:0 clickhouse.altinity.com/clusterScopeIndex:2 clickhouse.altinity.com/namespace:live-clickhouse-operator clickhouse.altinity.com/replica:0 clickhouse.altinity.com/replicaScopeIndex:1 clickhouse.altinity.com/shard:1 clickhouse.altinity.com/shardScopeIndex:0]
ap item path:.VolumeClaimTemplates[0].Status.Phase
ap item value:
ap item path:.Template.Spec.InitContainers[0].TerminationMessagePolicy
ap item value:
ap item path:.Template.Spec.Containers[0].ImagePullPolicy
ap item value:
ap item path:.Template.Spec.DNSPolicy
ap item value:
ap item path:.Template.Spec.SecurityContext
ap item value:nil
ap item path:.VolumeClaimTemplates[0].Spec.Resources.Requests["storage"].i.value
ap item value:1717986918400
ap item path:.Template.Spec.Volumes[0].VolumeSource.HostPath.Type
ap item value:<nil>
ap item path:.Template.Spec.InitContainers[0].ImagePullPolicy
ap item value:
ap item path:.Template.Spec.Containers[0].Ports[0].Protocol
ap item value:
ap item path:.Template.Spec.Containers[0].Ports[1].Protocol
ap item value:
ap item path:.Template.Spec.Containers[0].Ports[2].Protocol
ap item value:
ap item path:.Template.Spec.TerminationGracePeriodSeconds
ap item value:<nil>
ap item path:.Template.Spec.SchedulerName
ap item value:
-------------------------
deleteStatefulSet(live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0) 
waitStatefulSetGeneration(live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0)-OK  :ObservedGeneration:2 Replicas:1 ReadyReplicas:0 CurrentReplicas:0 UpdatedReplicas:0 CurrentRevision:chi-analytics-2-ch-cluster-0-0-86c6ffc95c UpdateRevision:chi-analytics-2-ch-cluster-0-0-86c6ffc95c 
StatefulSet live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0 deleted 
cache synced 
Create StatefulSet live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0 - started 
Create StatefulSet live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0 
endpointsInformer UpdateFunc(live-clickhouse-operator/clickhouse-service-external-analytics-2) IP ASSIGNED [{[{10.x.x.x  0xc000923970 &ObjectReference{Kind:Pod,Namespace:live-clickhouse-operator,Name:chi-analytics-2-ch-cluster-0-0-0,UID:3288b71a-9d4c-4fff-ab37-0a423dd8945d,APIVersion:,ResourceVersion:14057442,FieldPath:,}} {10.x.x.x  0xc000923980 &ObjectReference{Kind:Pod,Namespace:live-clickhouse-operator,Name:chi-analytics-2-ch-cluster-1-0-0,UID:34e8a064-adba-4c3d-bc2b-f4784d85ea9c,APIVersion:,ResourceVersion:8470041,FieldPath:,}} {10.x.x.x  0xc000923990 &ObjectReference{Kind:Pod,Namespace:live-clickhouse-operator,Name:chi-analytics-2-ch-cluster-0-0-0,UID:d05ca2da-bd72-410f-a0b4-f83ec849ead7,APIVersion:,ResourceVersion:14057803,FieldPath:,}} {10.x.x.x  0xc0009239a0 &ObjectReference{Kind:Pod,Namespace:live-clickhouse-operator,Name:chi-analytics-2-ch-cluster-0-0-0,UID:4674dae8-1049-4b44-9db9-54fa45f0df40,APIVersion:,ResourceVersion:14057064,FieldPath:,}}] [] [{http 8123 TCP}]}] 
endpointsInformer UpdateFunc(live-clickhouse-operator/clickhouse-service-internal-analytics-2) IP ASSIGNED [{[{10.x.x.x  0xc00093f300 &ObjectReference{Kind:Pod,Namespace:live-clickhouse-operator,Name:chi-analytics-2-ch-cluster-0-0-0,UID:3288b71a-9d4c-4fff-ab37-0a423dd8945d,APIVersion:,ResourceVersion:14057442,FieldPath:,}} {10.x.x.x  0xc00093f310 &ObjectReference{Kind:Pod,Namespace:live-clickhouse-operator,Name:chi-analytics-2-ch-cluster-1-0-0,UID:34e8a064-adba-4c3d-bc2b-f4784d85ea9c,APIVersion:,ResourceVersion:8470041,FieldPath:,}} {10.x.x.x  0xc00093f320 &ObjectReference{Kind:Pod,Namespace:live-clickhouse-operator,Name:chi-analytics-2-ch-cluster-0-0-0,UID:d05ca2da-bd72-410f-a0b4-f83ec849ead7,APIVersion:,ResourceVersion:14057803,FieldPath:,}} {10.x.x.x  0xc00093f330 &ObjectReference{Kind:Pod,Namespace:live-clickhouse-operator,Name:chi-analytics-2-ch-cluster-0-0-0,UID:4674dae8-1049-4b44-9db9-54fa45f0df40,APIVersion:,ResourceVersion:14057064,FieldPath:,}}] [] [{client 9000 TCP} {http 8123 TCP}]}] 
waitStatefulSetGeneration(live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0)-OK  :ObservedGeneration:1 Replicas:1 ReadyReplicas:1 CurrentReplicas:1 UpdatedReplicas:1 CurrentRevision:chi-analytics-2-ch-cluster-0-0-7cff859cc4 UpdateRevision:chi-analytics-2-ch-cluster-0-0-7cff859cc4 
Create StatefulSet live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0 - completed 
CreateServiceHost(live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0) for Set chi-analytics-2-ch-cluster-0-0 
Update Service live-clickhouse-operator/chi-analytics-2-ch-cluster-0-0 
Reconcile Host 0-0 completed 
```

**Comment by alex-zaitsev** [comment] 2020-07-06 16:21
Hi @wiktor2200, how many pods do you have in total? Could you check that those were actually downgraded connecting with a clickhouse-client?

**Comment by wiktor2200** [comment] 2020-07-07 06:32
I've got 4 pods in total. (2 shards, 2 replicas). All of them has successfully downgraded, but one of the pods lost its table schema (and data). When I've run `CREATE TABLE ... ON CLUSTER` it gets it schema again and replication caught up to kept up-to-date.

**Comment by alex-zaitsev** [comment] 2020-07-07 06:36
Looks like the problem is that the pod has lost its storage completely. Are you using PVs? Where are you running the Kubernetes?

**Comment by wiktor2200** [comment] 2020-07-07 07:06
I'm running cluster in GCP (GKE ver. 1.16.8-gke.15) and using PVs (storageClass is set to `ssd-retain`), so even when pod's disk is disconnected and pod is getting the new one the old one remains in the list of storage volumes. In this case the disk has been reused but it seems to be formatted.

**Comment by alex-zaitsev** [comment] 2020-09-20 22:19
@wiktor2200, since we can not troubleshoot the problem, I will close this. Latests releases of operator handle upgrades/downgrades more carefully as well.

**Closed by alex-zaitsev** 2020-09-20 22:19 UTC
