### ISSUE TITLE
Operator Pod Memory leak

### ISSUE THREAD

**Issue by MetalRex101** [Altinity/clickhouse-operator#176] opened 2019-10-16 11:57 UTC
![image](https://user-images.githubusercontent.com/17021192/66916831-c3719300-f024-11e9-9ceb-e59ce5a906a6.png)

Operator version - 0.6.0

The problem is that after operator pod reach some memory limit, it would be Evicted by kubernetes. We have to manually clear these pods to prevent them from using resources.

**Comment by alex-zaitsev** [comment] 2019-10-29 22:02
@MetalRex101 , could you advise on your Kubernetes version and ClickHouse cluster setup. We can not reproduce memory leak in our environment. Could you check if you see it growing on 'clickhouse-operator' or 'metrics-exporter' container? It can be checked with a command like:

# kubectl top pod <your_operator_pod_name> --containers=true -n <your_namespace>

**Comment by MetalRex101** [comment] 2019-10-30 08:19
Kubenetes version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.15", GitCommit:"b48a8d693e191192e27c2f807daa51b54d0b0a61", GitTreeState:"clean", BuildDate:"2019-08-12T17:49:30Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
Operator pod top:
```
POD                                    NAME                  CPU(cores)   MEMORY(bytes)
clickhouse-operator-6b7f548688-m5857   clickhouse-operator   8m           36Mi
```

Clickhouse cluster configuration:
```
Name:         chi-clickhouse-db-common-configd
Namespace:    clickhouse
Labels:       clickhouse.altinity.com/app=chop
              clickhouse.altinity.com/chi=clickhouse-db
              clickhouse.altinity.com/chop=0.6.0
Annotations:  <none>

Data
====
remote_servers.xml:
----
<yandex>
    <remote_servers>
        <!-- User-specified clusters -->
        <default>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-clickhouse-db-default-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-clickhouse-db-default-0-1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-clickhouse-db-default-1-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-clickhouse-db-default-1-1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </default>
        <!-- Autogenerated clusters -->
        <all-replicated>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-clickhouse-db-default-0-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-clickhouse-db-default-0-1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-clickhouse-db-default-1-0</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>chi-clickhouse-db-default-1-1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </all-replicated>
        <all-sharded>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-clickhouse-db-default-0-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-clickhouse-db-default-0-1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-clickhouse-db-default-1-0</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>chi-clickhouse-db-default-1-1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </all-sharded>
    </remote_servers>
</yandex>

zookeeper.xml:
----
<yandex>
    <zookeeper>
        <node>
            <host>zookeeper-0.zookeeper-headless.clickhouse</host>
            <port>2181</port>
        </node>
        <node>
            <host>zookeeper-1.zookeeper-headless.clickhouse</host>
            <port>2181</port>
        </node>
        <node>
            <host>zookeeper-2.zookeeper-headless.clickhouse</host>
            <port>2181</port>
        </node>
    </zookeeper>
    <distributed_ddl>
        <path>/clickhouse/clickhouse-db/task_queue/ddl</path>
    </distributed_ddl>
</yandex>

01-clickhouse-operator-listen.xml:
----
<yandex>
    <!-- Listen wildcard address to allow accepting connections from other containers and host network. -->
    <listen_host>::</listen_host>
    <listen_host>0.0.0.0</listen_host>
    <listen_try>1</listen_try>
</yandex>

02-clickhouse-operator-logger.xml:
----
<yandex>
    <logger>
        <console>1</console>
    </logger>
</yandex>
```

**Comment by alex-zaitsev** [comment] 2019-10-30 10:21
Thanks, @MetalRex101 , do you have metrics exporter pod running? If you upgraded from 0.5.0, you could miss it. You can check your operator logs as well -- if metrics exporter is missing it complains a lot. This is a bug that is already fixed.

Also, please list your CHI spec, if possible. 

We are going to release 0.7.0 later this week, so we mainly test this version. Probably the memory issue is already fixed.

**Comment by MetalRex101** [comment] 2019-10-30 11:32
@alex-zaitsev, what is CHI spec? How could i get that?
If New release version is coming soon, we could wait for it and try for memory leaks. If no leaks will appear, we could close this issue. Is that ok for you?

**Comment by alex-zaitsev** [comment] 2019-10-30 12:00
@MetalRex101 , CHI spec is your ClickHouseInstallation resource specification.

**Comment by MetalRex101** [comment] 2019-10-30 12:49
```
Name:         clickhouseinstallations.clickhouse.altinity.com
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-08-22T13:20:12Z
  Generation:          1
  Resource Version:    69727706
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/clickhouseinstallations.clickhouse.altinity.com
  UID:                 927ecf47-c4df-11e9-bf9f-42010a9c0fc2
Spec:
  Additional Printer Columns:
    JSON Path:    .status.version
    Description:  Operator version
    Name:         version
    Type:         string
    JSON Path:    .status.clusters
    Description:  Clusters count
    Name:         clusters
    Type:         integer
    JSON Path:    .status.replicas
    Description:  Replicas count
    Name:         replicas
    Type:         integer
    JSON Path:    .status.endpoint
    Description:  Client access endpoint
    Name:         endpoint
    Type:         string
  Group:          clickhouse.altinity.com
  Names:
    Kind:       ClickHouseInstallation
    List Kind:  ClickHouseInstallationList
    Plural:     clickhouseinstallations
    Short Names:
      chi
    Singular:  clickhouseinstallation
  Scope:       Namespaced
  Validation:
    Open APIV 3 Schema:
      Properties:
        Spec:
          Properties:
            Configuration:
              Properties:
                Clusters:
                  Items:
                    Properties:
                      Layout:
                        Properties:
                          Replicas Count:
                            Type:  integer
                          Shards:
                            Items:
                              Properties:
                                Definition Type:
                                  Type:  string
                                Internal Replication:
                                  Type:  string
                                Name:
                                  Pattern:  ^([a-zA-Z0-9_-]){0,8}$
                                  Type:     string
                                Replicas:
                                  Items:
                                    Properties:
                                      Name:
                                        Pattern:  ^([a-zA-Z0-9_-]){0,8}$
                                        Type:     string
                                      Port:
                                        Minimum:  1
                                        Type:     integer
                                      Templates:
                                        Properties:
                                          Cluster Service Template:
                                            Type:  string
                                          Pod Template:
                                            Type:  string
                                          Replica Service Template:
                                            Type:  string
                                          Service Template:
                                            Type:  string
                                          Shard Service Template:
                                            Type:  string
                                          Volume Claim Template:
                                            Type:  string
                                        Type:      object
                                    Type:          object
                                  Type:            array
                                Replicas Count:
                                  Minimum:  1
                                  Type:     integer
                                Templates:
                                  Properties:
                                    Cluster Service Template:
                                      Type:  string
                                    Pod Template:
                                      Type:  string
                                    Replica Service Template:
                                      Type:  string
                                    Service Template:
                                      Type:  string
                                    Shard Service Template:
                                      Type:  string
                                    Volume Claim Template:
                                      Type:  string
                                  Type:      object
                                Weight:
                                  Type:  integer
                              Type:      object
                            Type:        array
                          Shards Count:
                            Type:  integer
                          Type:
                            Type:  string
                        Type:      object
                      Name:
                        Pattern:  ^[a-zA-Z]([a-zA-Z0-9_-]){0,14}$
                        Type:     string
                      Replicas Count:
                        Minimum:  1
                        Type:     integer
                      Shards Count:
                        Minimum:  1
                        Type:     integer
                      Templates:
                        Properties:
                          Cluster Service Template:
                            Type:  string
                          Pod Template:
                            Type:  string
                          Replica Service Template:
                            Type:  string
                          Service Template:
                            Type:  string
                          Shard Service Template:
                            Type:  string
                          Volume Claim Template:
                            Type:  string
                        Type:      object
                    Required:
                      name
                    Type:  object
                  Type:    array
                Profiles:
                  Type:  object
                Quotas:
                  Type:  object
                Settings:
                  Type:  object
                Users:
                  Type:  object
                Zookeeper:
                  Properties:
                    Nodes:
                      Items:
                        Properties:
                          Host:
                            Type:  string
                          Port:
                            Minimum:  1
                            Type:     integer
                        Required:
                          host
                        Type:  object
                      Type:    array
                  Type:        object
              Type:            object
            Defaults:
              Properties:
                Distributed DDL:
                  Properties:
                    Profile:
                      Type:  string
                  Type:      object
                Replicas Use FQDN:
                  Type:  string
                Templates:
                  Properties:
                    Cluster Service Template:
                      Type:  string
                    Pod Template:
                      Type:  string
                    Replica Service Template:
                      Type:  string
                    Service Template:
                      Type:  string
                    Shard Service Template:
                      Type:  string
                    Volume Claim Template:
                      Type:  string
                  Type:      object
              Type:          object
            Templates:
              Properties:
                Pod Templates:
                  Items:
                    Required:
                      name
                      spec
                    Type:  object
                  Type:    array
                Service Templates:
                  Items:
                    Properties:
                      Generate Name:
                        Type:  string
                      Name:
                        Type:  string
                      Spec:
                        Type:  object
                    Required:
                      name
                      spec
                    Type:  object
                  Type:    array
                Volume Claim Templates:
                  Items:
                    Properties:
                      Name:
                        Type:  string
                      Reclaim Policy:
                        Enum:
                          Retain
                          Delete
                        Type:  string
                      Spec:
                        Type:  object
                    Required:
                      name
                      spec
                    Type:  object
                  Type:    array
              Type:        object
          Type:            object
  Version:                 v1
  Versions:
    Name:     v1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       ClickHouseInstallation
    List Kind:  ClickHouseInstallationList
    Plural:     clickhouseinstallations
    Short Names:
      chi
    Singular:  clickhouseinstallation
  Conditions:
    Last Transition Time:  2019-08-22T13:20:12Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
```

**Comment by lukatera** [comment] 2020-02-04 07:36
We have similar issue but with version 0.8.0. Our operator pod is constantly getting evicted because of too high resource usage. Now that metrics have been separated from operator, we can see that it is metrics pod which is using a lot of memory. It's using over 2GiB before getting evicted which seems way too much just for metrics.

**Comment by alex-zaitsev** [comment] 2020-02-04 07:44
@lukatera , what is the size of your cluster and do you actually use monitoring? (i.e. Prometheus integration).

**Comment by lukatera** [comment] 2020-02-04 07:46
Size of the cluster is 8 shards * 2 times replicated. We use Prometheus to collect metrics from clickhouse-metrics.

**Comment by lukatera** [comment] 2020-02-04 07:51
Here's the graph of `container_memory_usage_bytes{container_name="metrics-exporter"}` over past day.
![Screen Shot 2020-02-04 at 8 49 36 AM](https://user-images.githubusercontent.com/43570291/73724362-70366400-472b-11ea-9db3-5e406bb64e86.png)

**Comment by alex-zaitsev** [comment] 2020-02-04 07:52
@lukatera , thanks. We are making some fixes to metrics exporter now, will look at possible memory  leak issue and provide a fix.

**Comment by guoshuai2016** [comment] 2020-02-20 08:13
any update here? we also encounter the same issue.

**Comment by alex-zaitsev** [comment] 2020-02-24 16:51
@guoshuai2016 , @lukatera , @MetalRex101 , the memory leak is not fixed yet, but we have fixed #239 in 0.9.1 release, so monitoring is not lost when metrics exporter pod is restarted. The memory leak itself is the next priority.

**Comment by guoshuai2016** [comment] 2020-02-26 01:27
@alex-zaitsev After pprof the heap and goroutine, we found the memory leak is caused by goroutine leak, specifically by too many opened sql.DB, which is created for each query. Every opened sql.DB will have two goroutines, like:
`goroutine 85 [select, 3528 minutes]:
database/sql.(*DB).connectionResetter(0xc0000b66c0, 0x135d160, 0xc0000b2f80)
        /usr/local/go/src/database/sql/sql.go:1013 +0xfb
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:671 +0x194

goroutine 47 [select, 3528 minutes]:
database/sql.(*DB).connectionOpener(0xc0000b6600, 0x135d160, 0xc0000b2600)
        /usr/local/go/src/database/sql/sql.go:1000 +0xe8
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:670 +0x15e`

Thus the quick fix solution is to close the sql.DB after query, however this is not recommended:
`// The returned DB is safe for concurrent use by multiple goroutines
// and maintains its own pool of idle connections. Thus, the Open
// function should be called just once. It is rarely necessary to
// close a DB.
func Open(driverName, dataSourceName string) (*DB, error) {`

So I keep the sql.DB in a global map, which works as singleton. [#270 ]

Apart from the leak, we also find the `clickHouseQueryScanRows` may return partial data, after Investigation, we found it caused by sql.Rows is closed by deadline context after query but before scan. So we refine to close the deadline context  after scan. [#270 ]


Those changes has been tested on our Stage and Production environment. Please help review the merge request.

**Comment by sunsingerus** [comment] 2020-02-26 20:07
fix merged into [0.9.2](https://github.com/Altinity/clickhouse-operator/tree/0.9.2), thanks @guoshuai2016

**Comment by sunsingerus** [comment] 2020-02-26 20:07
Please, take a look

**Comment by alex-zaitsev** [comment] 2020-02-28 13:00
Fixed in https://github.com/Altinity/clickhouse-operator/releases/tag/0.9.2

**Closed by alex-zaitsev** 2020-02-28 13:00 UTC
Labels: fix proposed, possible bug, research required
