### ISSUE TITLE
sudden disappearance of CHI pods

### ISSUE THREAD

**Issue by prashant-shahi** [Altinity/clickhouse-operator#1221] opened 2023-08-21 05:39 UTC
After running the clickhouse for couple of months, the CHI pod has disappeared on its own.

@hodgesrm had advised on adding `stop: "no"` for fix. However, I had already resolved by changing shard count and reverting, to trigger re-creation of CHI pod (by changing state of CHI out of completed to force pod re-creation).

Nevertheless, we had been unable to find the root cause of the issue. So, this issue could re-appear in the future.

CHI definition:

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: my-release-clickhouse
  namespace: default
  labels:
    helm.sh/chart: clickhouse-23.12.2
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/version: "22.8.8"
    app.kubernetes.io/managed-by: Helm
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volumeclaim-template
      serviceTemplate: service-template

  configuration:
    users:
      admin/password: redacted
      admin/networks/ip:
        - "10.0.0.0/8"
        - "100.64.0.0/10"
        - "172.16.0.0/12"
        - "192.0.0.0/24"
        - "198.18.0.0/15"
        - "192.168.0.0/16"
      admin/profile: default
      admin/quota: default

    profiles:
      default/allow_experimental_window_functions: "1"
      default/allow_nondeterministic_mutations: "1"

    clusters:
      - name: "cluster"
        templates:
          podTemplate: pod-template
        layout:
          replicasCount: 1
          shardsCount: 1

    settings:
      format_schema_path: /etc/clickhouse-server/config.d/
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      user_defined_executable_functions_config: /etc/clickhouse-server/functions/custom-functions.xml
      user_scripts_path: /var/lib/clickhouse/user_scripts/

    files:
      events.proto: |
        syntax = "proto3";
        message Event {
          string uuid = 1;
          string event = 2;
          string properties = 3;
          string timestamp = 4;
          uint64 team_id = 5;
          string distinct_id = 6;
          string created_at = 7;
          string elements_chain = 8;
        }
    zookeeper:
      nodes:
        - host: my-release-zookeeper-0.my-release-zookeeper-headless
          port: 2181

  templates:
    podTemplates:
      - name: pod-template
        metadata:
          labels:
            helm.sh/chart: clickhouse-23.12.2
            app.kubernetes.io/name: clickhouse
            app.kubernetes.io/instance: my-release
            app.kubernetes.io/component: clickhouse
            app.kubernetes.io/version: "22.8.8"
            app.kubernetes.io/managed-by: Helm
          annotations: {}
        podDistribution:
          - topologyKey: kubernetes.io/hostname
            type: ReplicaAntiAffinity
        spec:          
          serviceAccountName: my-release-clickhouse
          priorityClassName: ""
          securityContext:
            fsGroup: 101
            runAsGroup: 101
            runAsUser: 101

          volumes:
            - name: shared-binary-volume
              emptyDir: {}
            - name: custom-functions-volume
              configMap:
                name: my-release-clickhouse-custom-functions
          initContainers: []
          containers:
            - name: clickhouse
              image: docker.io/clickhouse/clickhouse-server:22.8.8-alpine
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml

              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009

              volumeMounts:
                - name: data-volumeclaim-template
                  mountPath: /var/lib/clickhouse
                - name: shared-binary-volume
                  mountPath: /var/lib/clickhouse/user_scripts
                - name: custom-functions-volume
                  mountPath: /etc/clickhouse-server/functions
              resources: 
                requests:
                  cpu: 100m
                  memory: 200Mi

    serviceTemplates:
      - name: service-template
        generateName: my-release-clickhouse
        metadata:
          labels:
            helm.sh/chart: clickhouse-23.12.2
            app.kubernetes.io/name: clickhouse
            app.kubernetes.io/instance: my-release
            app.kubernetes.io/component: clickhouse
            app.kubernetes.io/version: "22.8.8"
            app.kubernetes.io/managed-by: Helm
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 8123
              nodePort: null
            - name: tcp
              port: 9000
              nodePort: null
    volumeClaimTemplates:
      - name: data-volumeclaim-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: standard
```

Context: [Slack Message](https://altinitydbworkspace.slack.com/archives/C02K1MWEK2L/p1692251839060289)

**Comment by Slach** [comment] 2023-08-21 08:35
Is your `kind: ClickHouseInstallation` managed by the same Helm chart with `clickhouse-operator`?

Could you share the following commands?
```
kubectl get deploy --all-namespaces -l app=clickhouse-operator
kubectl get pod --all-namespaces -l clickhouse.altinity.com/chi
```

**Comment by prashant-shahi** [comment] 2023-08-21 10:59
@Slach Yes, it is managed by the same chart with `clickhouse-operator`.

```
kubectl get deploy --all-namespaces app.kubernetes.io/component=operator

NAMESPACE     NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
default       my-release-clickhouse-operator              1/1     1            1           60d
test          my-release-clickhouse-operator              1/1     1            1           38d
```

```
kubectl get pod --all-namespaces -l clickhouse.altinity.com/chi

NAMESPACE     NAME                                                 READY   STATUS    RESTARTS        AGE
default       chi-my-release-clickhouse-cluster-0-0-0              1/1     Running   0               3d21h
test          chi-my-release-clickhouse-cluster-0-0-0              1/1     Running   0               4d19h
```

**Comment by Slach** [comment] 2023-08-21 16:19
could you share operator logs from test namespace?

`kubectl logs -n test -l app.kubernetes.io/component=operator --since=7d`

**Comment by prashant-shahi** [comment] 2023-08-23 09:29
I was getting the error below:

```
error: invalid argument "7d" for "--since" flag: time: unknown unit "d" in duration "7d"
```

Hence, replaced `7d` with `168h`:

```
$ kubectl logs -n test -l app.kubernetes.io/component=operator --since=168h

Defaulted container "my-release-clickhouse-operator" out of: my-release-clickhouse-operator, my-release-clickhouse-metrics-exporter
E0822 10:51:33.116468       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.124.0.1:443/api/v1/namespaces/test/services?resourceVersion=101836934": dial tcp 10.124.0.1:443: i/o timeout
I0822 10:51:38.125884       1 trace.go:205] Trace[301511361]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (22-Aug-2023 10:51:08.124) (total time: 30001ms):
Trace[301511361]: [30.00114905s] [30.00114905s] END
E0822 10:51:38.125902       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: Get "https://10.124.0.1:443/apis/apps/v1/namespaces/test/statefulsets?resourceVersion=101836529": dial tcp 10.124.0.1:443: i/o timeout
I0822 10:51:38.355293       1 trace.go:205] Trace[2060365486]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (22-Aug-2023 10:51:08.354) (total time: 30001ms):
Trace[2060365486]: [30.001212232s] [30.001212232s] END
E0822 10:51:38.355312       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.124.0.1:443/api/v1/namespaces/test/configmaps?resourceVersion=101837009": dial tcp 10.124.0.1:443: i/o timeout
I0822 10:51:42.173930       1 trace.go:205] Trace[250496038]: "Reflector ListAndWatch" name:pkg/client/informers/externalversions/factory.go:117 (22-Aug-2023 10:51:12.172) (total time: 30001ms):
Trace[250496038]: [30.001189387s] [30.001189387s] END
E0822 10:51:42.173949       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseOperatorConfiguration: failed to list *v1.ClickHouseOperatorConfiguration: Get "https://10.124.0.1:443/apis/clickhouse.altinity.com/v1/namespaces/test/clickhouseoperatorconfigurations?resourceVersion=101836611": dial tcp 10.124.0.1:443: i/o timeout
```


```
$ kubectl logs -n default -l app.kubernetes.io/component=operator --since=168h

Defaulted container "my-release-clickhouse-operator" out of: my-release-clickhouse-operator, my-release-clickhouse-metrics-exporter
E0822 10:51:38.591455       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.124.0.1:443/api/v1/namespaces/default/services?resourceVersion=101836934": dial tcp 10.124.0.1:443: i/o timeout
I0822 10:51:41.314893       1 trace.go:205] Trace[1051692860]: "Reflector ListAndWatch" name:pkg/client/informers/externalversions/factory.go:117 (22-Aug-2023 10:51:11.313) (total time: 30001ms):
Trace[1051692860]: [30.001164853s] [30.001164853s] END
E0822 10:51:41.314912       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseOperatorConfiguration: failed to list *v1.ClickHouseOperatorConfiguration: Get "https://10.124.0.1:443/apis/clickhouse.altinity.com/v1/namespaces/default/clickhouseoperatorconfigurations?resourceVersion=101836881": dial tcp 10.124.0.1:443: i/o timeout
I0822 10:51:41.768145       1 trace.go:205] Trace[523315261]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (22-Aug-2023 10:51:11.767) (total time: 30000ms):
Trace[523315261]: [30.000906333s] [30.000906333s] END
E0822 10:51:41.768163       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.124.0.1:443/api/v1/namespaces/default/configmaps?resourceVersion=101837009": dial tcp 10.124.0.1:443: i/o timeout
I0822 10:51:42.946368       1 trace.go:205] Trace[838394852]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (22-Aug-2023 10:51:12.945) (total time: 30000ms):
Trace[838394852]: [30.000528326s] [30.000528326s] END
E0822 10:51:42.946386       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://10.124.0.1:443/api/v1/namespaces/default/pods?resourceVersion=101836916": dial tcp 10.124.0.1:443: i/o timeout
```

**Comment by Slach** [comment] 2023-08-26 16:14
looks like nothing happens 22 Aug

Could you share?

```
kubectl logs -n default -l app.kubernetes.io/component=operator -c clickhouse-operator
kubectl logs -n test -l app.kubernetes.io/component=operator -c clickhouse-operator
```

**Comment by prashant-shahi** [comment] 2023-08-26 19:38
Sure, here are the logs:

```
$ kubectl logs -n default -l app.kubernetes.io/component=operator -c my-release-clickhouse-operator

I0823 18:03:06.328611       1 worker-reconciler.go:111] worker-reconciler.go:52:reconcileCHI():end:default/my-release-clickhouse
I0823 18:03:06.328632       1 worker.go:414] worker.go:380:updateCHI():end:default/my-release-clickhouse
E0823 18:03:49.676857       1 connection.go:190] Exec():FAILED Exec(http://clickhouse_operator:***@chi-my-release-clickhouse-cluster-0-0.default.svc.cluster.local:8123/) context deadline exceeded for SQL: SYSTEM DROP DNS CACHE
W0823 18:03:49.712800       1 retry.go:52] exec():chi-my-release-clickhouse-cluster-0-0.default.svc.cluster.local:FAILED single try. No retries will be made for Applying sqls
I0823 18:03:49.801384       1 worker.go:339] default/my-release-clickhouse/5d89fdfb-a136-430a-a8a5-310c07edef5b:IPs of the CHI-1 [10.120.1.155]
I0823 18:03:49.812084       1 worker.go:343] default/my-release-clickhouse/13b958a0-3cfd-46a6-a3ce-368a46cc97df:Update users IPS-1
I0823 18:03:49.821067       1 worker.go:1089] updateConfigMap():default/my-release-clickhouse/13b958a0-3cfd-46a6-a3ce-368a46cc97df:Update ConfigMap default/chi-my-release-clickhouse-common-usersd
I0823 18:03:49.903031       1 worker.go:339] default/my-release-clickhouse/88d992b4-a76a-4a2b-af19-2cc81d64548a:IPs of the CHI-1 [10.120.1.155]
I0823 18:03:49.910434       1 worker.go:343] default/my-release-clickhouse/5892dd12-16a8-4e6f-baf6-e5ec8776277d:Update users IPS-1
I0823 18:03:49.914824       1 worker.go:1089] updateConfigMap():default/my-release-clickhouse/5892dd12-16a8-4e6f-baf6-e5ec8776277d:Update ConfigMap default/chi-my-release-clickhouse-common-usersd
```

```
$ kubectl logs -n test -l app.kubernetes.io/component=operator -c my-release-clickhouse-operator

I0823 17:13:58.953558       1 worker-deleter.go:64] worker-deleter.go:64:dropReplicas():start:test/my-release-clickhouse/f3f569fa-3d23-4b03-a914-71c7bf07cf7d:drop replicas based on AP
I0823 17:13:58.953588       1 worker-deleter.go:81] worker-deleter.go:81:dropReplicas():end:test/my-release-clickhouse/f3f569fa-3d23-4b03-a914-71c7bf07cf7d:processed replicas: 0
I0823 17:13:58.953612       1 worker.go:573] includeStopped():test/my-release-clickhouse/f3f569fa-3d23-4b03-a914-71c7bf07cf7d:add CHI to monitoring
I0823 17:13:59.355282       1 controller.go:609] OK update watch (test/my-release-clickhouse): {"namespace":"test","name":"my-release-clickhouse","clusters":[{"name":"cluster","hosts":[{"name":"0-0","hostname":"chi-my-release-clickhouse-cluster-0-0.test.svc.cluster.local","tcpPort":9000,"httpPort":8123}]}]}
I0823 17:13:59.360534       1 worker.go:540] test/my-release-clickhouse:all IP addresses are in place
I0823 17:13:59.526393       1 worker.go:611] test/my-release-clickhouse/7de65ad0-12b1-4823-8657-ca1e4984bb8f:IPs of the CHI-2 [10.120.1.133]
I0823 17:13:59.534938       1 worker.go:615] test/my-release-clickhouse/789d4f97-3cee-499d-9e78-631399e02bea:Update users IPS-2
I0823 17:13:59.748918       1 worker.go:636] finalizeReconcileAndMarkCompleted():test/my-release-clickhouse/f3f569fa-3d23-4b03-a914-71c7bf07cf7d:reconcile completed successfully, task id: f3f569fa-3d23-4b03-a914-71c7bf07cf7d
I0823 17:14:00.146065       1 worker-reconciler.go:111] worker-reconciler.go:52:reconcileCHI():end:test/my-release-clickhouse
I0823 17:14:00.146085       1 worker.go:414] worker.go:380:updateCHI():end:test/my-release-clickhouse
```

**Comment by Slach** [comment] 2023-08-27 06:57
=( this is not a full logs, this is only logs for 23 Aug

**Comment by prashant-shahi** [comment] 2023-08-27 09:50
@Slach This is all that there is. :(

**Comment by alex-zaitsev** [comment] 2023-09-22 08:03
Closing it as it is not reproducible. Could be something related to Helm

**Closed by alex-zaitsev** 2023-09-22 08:03 UTC

**Comment by prashant-shahi** [comment] 2024-07-29 06:22
@alex-zaitsev This is happening more often in recent time when trying to increase the ClickHouse PVC size in ClickHouse installation. Not able to pin point the root cause of the issue.

_Operator logs:_

```
I0729 03:49:26.917146       1 worker.go:1089] updateConfigMap():my-release/my-release-clickhouse/58053693-2b8a-4d1d-b5ed-e0432448d655:Update ConfigMap my-release/chi-my-release-clickhouse-deploy-confd-cluster-0-0
I0729 03:49:27.928385       1 cluster.go:84] Run query on: chi-my-release-clickhouse-cluster-0-0.my-release.svc.cluster.local of [chi-my-release-clickhouse-cluster-0-0.my-release.svc.cluster.local]
I0729 03:49:28.033592       1 worker-reconciler.go:292] reconcileHostStatefulSet():Reconcile host 0-0. ClickHouse version: 24.1.2.5
I0729 03:49:28.033769       1 worker.go:134] shouldForceRestartHost():Force restart is not required. Host: 0-0
I0729 03:49:28.033802       1 worker-reconciler.go:304] reconcileHostStatefulSet():Reconcile host 0-0. Reconcile StatefulSet
I0729 03:49:28.033959       1 creator.go:589] getPodTemplate():my-release/my-release-clickhouse/58053693-2b8a-4d1d-b5ed-e0432448d655:statefulSet chi-my-release-clickhouse-cluster-0-0 use custom template: pod-template
W0729 03:49:28.034289       1 creator.go:994] containerAppendVolumeMount():my-release/my-release-clickhouse/58053693-2b8a-4d1d-b5ed-e0432448d655:container.Name:clickhouse volumeMount.Name:data-volumeclaim-template already used
I0729 03:49:28.036205       1 worker.go:1290] getStatefulSetStatus():my-release/chi-my-release-clickhouse-cluster-0-0:cur and new StatefulSets ARE DIFFERENT based on labels. StatefulSet reconcile is required for: my-release/chi-my-release-clickhouse-cluster-0-0
I0729 03:49:28.036374       1 worker.go:1431] updateStatefulSet():Update StatefulSet(my-release/chi-my-release-clickhouse-cluster-0-0) - started
I0729 03:49:28.348502       1 worker.go:1401] waitConfigMapPropagation():Wait for ConfigMap propagation for 9.003953254s 996.046746ms/10s
E0729 03:49:37.360361       1 creator.go:76] updateStatefulSet():StatefulSet update failed. err: StatefulSet.apps "chi-my-release-clickhouse-cluster-0-0" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
E0729 03:49:37.361923       1 creator.go:100] updateStatefulSet():NOT EQUAL: AP item start -------------------------
modified spec items: 24
ap item path [0]:'.Template.Spec.Volumes[1].VolumeSource.ConfigMap.DefaultMode'
ap item value[0]:'nil'
ap item path [1]:'.Template.Spec.Containers[0].LivenessProbe.SuccessThreshold'
ap item value[1]:'0'
ap item path [2]:'.Template.Spec.Containers[0].ReadinessProbe.Handler.HTTPGet.Scheme'
ap item value[2]:'""'
ap item path [3]:'.Template.Spec.SchedulerName'
ap item value[3]:'""'
ap item path [4]:'.Template.Spec.Containers[0].LivenessProbe.Handler.HTTPGet.Scheme'
--
I0729 03:49:42.476651       1 poller.go:213] pollStatefulSet():my-release/chi-my-release-clickhouse-cluster-0-0:OK  :ObservedGeneration:2 Replicas:1 ReadyReplicas:1 CurrentReplicas:0 UpdatedReplicas:0 CurrentRevision:chi-my-release-clickhouse-cluster-0-0-8f9b7b45b UpdateRevision:chi-my-release-clickhouse-cluster-0-0-8f9b7b45b
W0729 03:50:27.487009       1 reflector.go:436] pkg/client/informers/externalversions/factory.go:117: watch of *v1.ClickHouseInstallation ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0729 03:50:27.487049       1 reflector.go:436] k8s.io/client-go/informers/factory.go:134: watch of *v1.StatefulSet ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0729 03:50:27.487052       1 reflector.go:436] k8s.io/client-go/informers/factory.go:134: watch of *v1.Endpoints ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0729 03:50:27.487012       1 reflector.go:436] k8s.io/client-go/informers/factory.go:134: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0729 03:50:27.487096       1 reflector.go:436] k8s.io/client-go/informers/factory.go:134: watch of *v1.ConfigMap ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0729 03:50:27.487127       1 reflector.go:436] pkg/client/informers/externalversions/factory.go:117: watch of *v1.ClickHouseInstallationTemplate ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0729 03:50:27.487145       1 reflector.go:436] k8s.io/client-go/informers/factory.go:134: watch of *v1.Pod ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0729 03:50:27.487294       1 reflector.go:436] pkg/client/informers/externalversions/factory.go:117: watch of *v1.ClickHouseOperatorConfiguration ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
I0729 03:50:27.488331       1 labeler.go:292] deleteLabelReadyPod():FAIL get pod for host 'my-release/0-0' err: Get "https://10.92.0.1:443/api/v1/namespaces/my-release/pods/chi-my-release-clickhouse-cluster-0-0-0": http2: client connection lost
E0729 03:50:57.489774       1 poller.go:237] pollStatefulSet():my-release/chi-my-release-clickhouse-cluster-0-0:my-release/chi-my-release-clickhouse-cluster-0-0 Get() FAILED
I0729 03:50:58.323884       1 trace.go:205] Trace[1632088119]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (29-Jul-2024 03:50:28.323) (total time: 30000ms):
Trace[1632088119]: [30.000791007s] [30.000791007s] END
E0729 03:50:58.323928       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://10.92.0.1:443/api/v1/namespaces/my-release/pods?resourceVersion=409134742": dial tcp 10.92.0.1:443: i/o timeout
I0729 03:50:58.387047       1 trace.go:205] Trace[1562350316]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (29-Jul-2024 03:50:28.386) (total time: 30000ms):
Trace[1562350316]: [30.000679957s] [30.000679957s] END
E0729 03:50:58.387074       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: Get "https://10.92.0.1:443/apis/apps/v1/namespaces/my-release/statefulsets?resourceVersion=409134694": dial tcp 10.92.0.1:443: i/o timeout
I0729 03:50:58.482514       1 trace.go:205] Trace[1523333257]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (29-Jul-2024 03:50:28.481) (total time: 30000ms):
Trace[1523333257]: [30.000761918s] [30.000761918s] END
E0729 03:50:58.482587       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.92.0.1:443/api/v1/namespaces/my-release/configmaps?resourceVersion=409134621": dial tcp 10.92.0.1:443: i/o timeout
I0729 03:50:58.627969       1 trace.go:205] Trace[328066567]: "Reflector ListAndWatch" name:pkg/client/informers/externalversions/factory.go:117 (29-Jul-2024 03:50:28.626) (total time: 30001ms):
Trace[328066567]: [30.001690277s] [30.001690277s] END
E0729 03:50:58.627999       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseOperatorConfiguration: failed to list *v1.ClickHouseOperatorConfiguration: Get "https://10.92.0.1:443/apis/clickhouse.altinity.com/v1/namespaces/my-release/clickhouseoperatorconfigurations?resourceVersion=409134300": dial tcp 10.92.0.1:443: i/o timeout
I0729 03:50:58.680316       1 trace.go:205] Trace[1867447287]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (29-Jul-2024 03:50:28.679) (total time: 30000ms):
Trace[1867447287]: [30.000683297s] [30.000683297s] END
E0729 03:50:58.680433       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.92.0.1:443/api/v1/namespaces/my-release/services?resourceVersion=409134696": dial tcp 10.92.0.1:443: i/o timeout
I0729 03:50:58.870657       1 trace.go:205] Trace[321750039]: "Reflector ListAndWatch" name:pkg/client/informers/externalversions/factory.go:117 (29-Jul-2024 03:50:28.869) (total time: 30000ms):
Trace[321750039]: [30.000749817s] [30.000749817s] END
E0729 03:50:58.870684       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseInstallation: failed to list *v1.ClickHouseInstallation: Get "https://10.92.0.1:443/apis/clickhouse.altinity.com/v1/namespaces/my-release/clickhouseinstallations?resourceVersion=409134690": dial tcp 10.92.0.1:443: i/o timeout
I0729 03:50:59.038154       1 trace.go:205] Trace[345492881]: "Reflector ListAndWatch" name:pkg/client/informers/externalversions/factory.go:117 (29-Jul-2024 03:50:29.037) (total time: 30000ms):
Trace[345492881]: [30.000824067s] [30.000824067s] END
E0729 03:50:59.038264       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseInstallationTemplate: failed to list *v1.ClickHouseInstallationTemplate: Get "https://10.92.0.1:443/apis/clickhouse.altinity.com/v1/namespaces/my-release/clickhouseinstallationtemplates?resourceVersion=409134495": dial tcp 10.92.0.1:443: i/o timeout
I0729 03:50:59.057219       1 trace.go:205] Trace[1113844881]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (29-Jul-2024 03:50:29.056) (total time: 30000ms):
Trace[1113844881]: [30.000738938s] [30.000738938s] END
E0729 03:50:59.057261       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.92.0.1:443/api/v1/namespaces/my-release/endpoints?resourceVersion=409134706": dial tcp 10.92.0.1:443: i/o timeout
```

**Comment by prashant-shahi** [comment] 2024-07-31 05:59
@alex-zaitsev @Slach can you please help here?

**Comment by Slach** [comment] 2024-07-31 09:18
Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.92.0.1:443/api/v1/namespaces/my-release/endpoints?resourceVersion=409134706": dial tcp 10.92.0.1:443: i/o timeout

means something wrong with your kubernetes API server
